namespace VPBANK.RMD.EFCore.Entities.SchemaInfos
{
    public class SchemaSqlQuery
    {
        public const string INFORMATION_SCHEMA_TABLES = "SELECT * FROM INFORMATION_SCHEMA.TABLES";
        public const string INFORMATION_SCHEMA_COLUMNS = "SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, ORDINAL_POSITION, COLUMN_DEFAULT, IS_NULLABLE, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE FROM INFORMATION_SCHEMA.COLUMNS";
    }
}
