<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VPBANK.RMD.Data.PhoenixConf\VPBANK.RMD.Data.PhoenixConf.csproj" />
    <ProjectReference Include="..\VPBANK.RMD.Repositories.PhoenixConf\VPBANK.RMD.Repositories.PhoenixConf.csproj" />
  </ItemGroup>

</Project>
