<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VPBANK.RMD.Repositories.PhoenixData\VPBANK.RMD.Repositories.PhoenixData.csproj" />
    <ProjectReference Include="..\VPBANK.RMD.Utils.Common\VPBANK.RMD.Utils.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DataContracts\" />
  </ItemGroup>

</Project>
